# Generated by Django 2.1.7 on 2019-03-07 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(max_length=20)),
                ('adult', models.IntegerField(default=0)),
                ('child', models.IntegerField(default=0)),
                ('note', models.TextField()),
                ('arrive_date', models.DateField()),
                ('depart_date', models.DateField()),
                ('is_breakfast', models.BooleanField(default=True)),
                ('price_booking', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelmanagement.Client')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelmanagement.RoomType')),
                ('room_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelmanagement.RoomStatus')),
            ],
        ),
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.IntegerField(default=0)),
                ('date_pay', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelmanagement.Booking')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelmanagement.PaymentType')),
            ],
        ),
        migrations.CreateModel(
            name='MinibarCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('date_order', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelmanagement.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelmanagement.RoomType')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=0)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelmanagement.RoomType')),
            ],
        ),
        migrations.CreateModel(
            name='RoomCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_confirm', models.IntegerField(default=0)),
                ('date_charge', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelmanagement.Booking')),
            ],
        ),
        migrations.AddField(
            model_name='minibarcharge',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelmanagement.Product'),
        ),
    ]
