# Generated by Django 2.1.7 on 2019-03-07 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0002_auto_20190307_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelmanagement.Booking')),
            ],
        ),
    ]
